name: Release Drafter CI
on:
  workflow_call:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4 #v5.15.0
        with:
          disable-releaser: ${{ github.ref_name != github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
